import { ICourse } from "../interfaces/ICourse";

export const sampleCourse: ICourse = {
  course: {
    term: "Autumn 2022",
    effectiveDate: "2018-01-07",
    effectiveStatus: "A",
    title: "Principles of Programming Languages",
    shortDescription: "Prin Prgrmng Langs",
    description:
      "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
    equivalentId: "",
    allowMultiEnroll: "N",
    maxUnits: 3,
    minUnits: 3,
    repeatUnitsLimit: 3,
    grading: "Graded",
    component: "Lecture",
    primaryComponent: "LEC",
    offeringNumber: "1",
    academicGroup: "Engineering",
    subject: "CSE",
    catalogNumber: "3341",
    campus: "Columbus",
    academicOrg: "D1435",
    academicCareer: "Undergraduate",
    cipCode: "14.0901",
    courseAttributes: [
      {
        name: "CCP",
        value: "LEVEL 1",
        description: "Level 1 CCP course",
      },
    ],
    campusCode: "COL",
    catalogLevel: "3xxx",
    subjectDesc: "Computer Science & Engineering",
    courseId: "150535",
  },
  sections: [
    {
      classNumber: "7154",
      section: "0010",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "BE0136",
          facilityType: "1B",
          facilityDescription: "Baker Systems Engineering",
          facilityDescriptionShort: "Baker Sys",
          facilityGroup: false,
          facilityCapacity: 40,
          buildingCode: "280",
          room: "136",
          buildingDescription: "Baker Systems 136",
          buildingDescriptionShort: "BE 136",
          startTime: "3:00 pm",
          endTime: "3:55 pm",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Timothy Carpenter",
              role: "PI",
              email: "carpenter.454@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
    {
      classNumber: "7177",
      section: "0020",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "PS0010",
          facilityType: "1C",
          facilityDescription: "Psychology Building",
          facilityDescriptionShort: "Psychology",
          facilityGroup: false,
          facilityCapacity: 60,
          buildingCode: "144",
          room: "010",
          buildingDescription: "Psychology Bldg 010",
          buildingDescriptionShort: "PS 010",
          startTime: "11:30 am",
          endTime: "12:25 pm",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Mike Bond",
              role: "PI",
              email: "bond.213@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
    {
      classNumber: "11855",
      section: "0050",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "JR0270",
          facilityType: "1B",
          facilityDescription: "Journalism Building",
          facilityDescriptionShort: "Journalism",
          facilityGroup: false,
          facilityCapacity: 72,
          buildingCode: "046",
          room: "270",
          buildingDescription: "Journalism Bldg 270",
          buildingDescriptionShort: "JR 270",
          startTime: "10:20 am",
          endTime: "11:15 am",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Neelam Soundarajan",
              role: "PI",
              email: "soundarajan.1@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
    {
      classNumber: "7895",
      section: "0060",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "CL0177",
          facilityType: "1B",
          facilityDescription: "Caldwell Laboratory",
          facilityDescriptionShort: "Caldwell",
          facilityGroup: false,
          facilityCapacity: 41,
          buildingCode: "026",
          room: "177",
          buildingDescription: "Caldwell Lab 177",
          buildingDescriptionShort: "CL 177",
          startTime: "12:40 pm",
          endTime: "1:35 pm",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Wayne Heym",
              role: "PI",
              email: "heym.1@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
    {
      classNumber: "8064",
      section: "0070",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "JR0270",
          facilityType: "1B",
          facilityDescription: "Journalism Building",
          facilityDescriptionShort: "Journalism",
          facilityGroup: false,
          facilityCapacity: 72,
          buildingCode: "046",
          room: "270",
          buildingDescription: "Journalism Bldg 270",
          buildingDescriptionShort: "JR 270",
          startTime: "9:10 am",
          endTime: "10:05 am",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Neelam Soundarajan",
              role: "PI",
              email: "soundarajan.1@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
    {
      classNumber: "35506",
      section: "0080",
      component: "Lecture",
      instructionMode: "In Person",
      meetings: [
        {
          meetingNumber: 1,
          facilityId: "PS0010",
          facilityType: "1C",
          facilityDescription: "Psychology Building",
          facilityDescriptionShort: "Psychology",
          facilityGroup: false,
          facilityCapacity: 60,
          buildingCode: "144",
          room: "010",
          buildingDescription: "Psychology Bldg 010",
          buildingDescriptionShort: "PS 010",
          startTime: "1:50 pm",
          endTime: "2:45 pm",
          startDate: "2022-08-23",
          endDate: "2022-12-07",
          monday: true,
          tuesday: false,
          wednesday: true,
          thursday: false,
          friday: true,
          saturday: false,
          sunday: false,
          standingMeetingPattern: null,
          instructors: [
            {
              displayName: "Mike Bond",
              role: "PI",
              email: "bond.213@osu.edu",
            },
          ],
        },
      ],
      courseOfferingNumber: 1,
      courseId: "150535",
      academicGroup: "ENG",
      subject: "Computer Science & Engineering",
      catalogNumber: "3341",
      career: "UGRD",
      description: "Prin Prgrmng Langs",
      enrollmentStatus: "Open",
      status: "A",
      type: "E",
      associatedClass: "10",
      autoEnrollWaitlist: true,
      autoEnrollSection1: null,
      autoEnrollSection2: null,
      consent: false,
      waitlistCapacity: 999,
      minimumEnrollment: 0,
      enrollmentTotal: 39,
      waitlistTotal: 0,
      academicOrg: "D1435",
      location: "CS-COLMBUS",
      equivalentCourseId: null,
      startDate: "2022-08-23",
      endDate: "2022-12-07",
      cancelDate: null,
      primaryInstructorSection: "0010",
      combinedSection: "Closed",
      holidaySchedule: "OSUSIS",
      sessionCode: "1",
      sessionDescription: "Regular Academic Term",
      term: "Autumn 2022",
      campus: "Columbus",
      attributes: [
        {
          name: "CCP",
          value: "LEVEL 1",
          description: "Level 1 CCP course",
        },
      ],
      secCampus: "COL",
      secAcademicGroup: "ENG",
      secCatalogNumber: "3341",
      meetingDays: "",
      _parent: "150535-1-1228",
      subjectDesc: "Computer Science & Engineering",
      courseTitle: "Principles of Programming Languages",
      courseDescription:
        "Formal languages and grammars; recursive descent parsing; data types, expressions, control structures, parameter passing; compilers and interpreters; memory management; functional programming principles.\nPrereq: 2231, 2331 (680), and 2421, and 3901 (560), 3902, or 3903. Not open to students with credit for 5341 (655).",
      catalogLevel: "3xxx",
      termCode: "1228",
    },
  ],
};
